name: bump_hls_js

on:
  schedule:
  - cron: '4 5 * * *'
  workflow_dispatch:

jobs:
  bump_hls_js:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: >
        git config user.name mediamtx-bot
        && git config user.email bot@mediamtx
        && ((git checkout deps/hlsjs && git rebase ${GITHUB_REF_NAME}) || git checkout -b deps/hlsjs)

    - run: |
        set -e
        VERSION=$(curl -s https://api.github.com/repos/video-dev/hls.js/releases?per_page=1 | grep tag_name | sed 's/\s\+"tag_name": "\(.\+\)",/\1/')
        HASH=$(curl -sL https://github.com/video-dev/hls.js/releases/download/$VERSION/release.zip -o- | sha256sum | cut -f1 -d ' ')
        echo $VERSION > internal/servers/hls/hlsjsdownloader/VERSION
        echo $HASH > internal/servers/hls/hlsjsdownloader/HASH
        echo VERSION=$VERSION >> $GITHUB_ENV

    - id: check_repo
      run: >
        echo "clean=$(git status --porcelain)" >> "$GITHUB_OUTPUT"

    - if: ${{ steps.check_repo.outputs.clean != '' }}
      run: >
        git reset ${GITHUB_REF_NAME}
        && git add .
        && git commit -m "bump hls.js to ${VERSION}"
        && git push --set-upstream origin deps/hlsjs --force

    - if: ${{ steps.check_repo.outputs.clean != '' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prs = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:deps/hlsjs`,
            state: 'open',
          });

          if (prs.data.length == 0) {
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'deps/hlsjs',
              base: context.ref.slice('refs/heads/'.length),
              title: `bump hls-js to ${process.env.VERSION}`,
            });
          } else {
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prs.data[0].number,
              title: `bump hls-js to ${process.env.VERSION}`,
            });
          }
