name: code_lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci_lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: "1.22"

    - run: go generate ./...

    - uses: golangci/golangci-lint-action@v4
      with:
        version: v1.55.0

  mod_tidy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v3
      with:
        go-version: "1.22"

    - run: make lint-mod-tidy

  api_docs:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - run: make lint-apidocs
